import React from 'react'
import { Routes, Route } from 'react-router-dom'
import AboutProject from 'Scenes/AboutProject'
import MainLayouts from 'Layouts/MainLayouts/MainLayouts'
import InitialScenes from 'Scenes/InitialScenes'
import Navigation from '../Components/Navigation'
